DEBUG    urllib3.connectionpool:connectionpool.py:206 Starting new HTTP connection (1): 47.97.206.151:8883
DEBUG    urllib3.connectionpool:connectionpool.py:396 http://47.97.206.151:8883 "POST /api/v1/login HTTP/1.1" 200 339
DEBUG    root:Log.py:74 [DEBUG2020-07-24 22-43-38]登录成功token为:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOjEwMDMzNDYsIkxvZ2luVmVyaWZ5IjowLCJleHAiOjE1OTU2NDUwMjB9.QWTukUNIGu-Rl-kaji5qsXFiRXE11JvvGgRq4uEDbnE
DEBUG    urllib3.connectionpool:connectionpool.py:206 Starting new HTTP connection (1): 47.97.206.151:3030
DEBUG    urllib3.connectionpool:connectionpool.py:396 http://47.97.206.151:3030 "POST /api-v2/activity/assetExchange/Exchange HTTP/1.1" 401 109
ERROR    root:Log.py:86 [ERROR2020-07-24 22-43-38]请求状态码对比失败,请求状态码为:401,断言状态码为:200